openapi: 3.0.3
info:
  title: Product Prices API for Spring Boot
  description: |-
    This is a documentation of the API for the Product Prices API for Spring Boot.

    -/api/v1/prices

  termsOfService: http://swagger.io/terms/
  contact:
    email: keybykey@pm.me
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost:8080/api/v1/
    description: Local server
tags:
  - name: prices
    description: All prices
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths: